version: '3.4'

services:
  rabbitmq:
   image: rabbitmq:3-management
   volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
   ports:
     - "15673:15672"
     - "5672:5672" 
  orderapi:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: OrderApi/Dockerfile
    depends_on:
       rabbitmq:
        condition: service_started
    ports:
      - 9000:80
      - 9001:443

  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: ProductApi/Dockerfile
    depends_on:
       rabbitmq:
        condition: service_started
    ports:
      - 9002:80
      - 9003:443


  customerapi:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: CustomerApi/Dockerfile
    depends_on:
       rabbitmq:
        condition: service_started
    ports:
      - 9004:80
      - 9005:443

